function Games(){};function Flash(){};Games.Common={};Games.Common.displayScore=function(){statusView.displayPoints("#status_points",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#status_percent",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#status_score",statusModel.getScore());statusView.displayLevel("#status_level",statusModel.getLevel());statusView.displayHiScore("#hi_score",statusModel.getHiScore())};
Games.Common.displaySummary=function(){$("#game_frame").hide();$("#staff_paper").hide();statusView.displayPoints("#point_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#percent_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#score_summary",statusModel.getScore());$("#time_summary_row").hide();$("#score_summary_row").show();$("#level_summary_row").show();$("#lives_summary_row").show();$("#next_level_row").show();$("#level_summary").html(""+
statusModel.getLevel());$("#lives_summary").html(""+statusModel.getLives());$("#summary_frame").show()};Games.Common.removeLivesDisplay=function(){statusView.removeLivesDisplay()};
Games.Common.displaySessionAlert=function(a,b,c){$("#menu_frame").hide();$("#instructions_frame").hide();$("#summary_frame").hide();$("#game_frame").hide();$("#staff_paper").hide();$("#menu_buttons").hide();$("#session_frame").show();$("#game_status_box").show();a&&!b?($("#session_start_header").html("Level "+statusModel.getLevel()),$("#session_end").hide(),$("#game_end").hide(),$("#session_start").show(),$("#session_start_button").focus()):b?($("#session_start").hide(),$("#session_end").hide(),$("#game_end").show(),
$("#scores_button").focus()):($("#session_start").hide(),$("#game_end").hide(),lives=statusModel.getLives(),lives_str=lives>1?" lives":" life",$("#lives").html(""+statusModel.getLives()+lives_str+" left"),c?($("#session_end_header").html("Good Job!"),$("#bonus").html("BONUS PTS<br/>"+statusModel.getBonus())):($("#session_end_header").html("Same Level"),$("#bonus").html("BONUS PTS<br/>0")),$("#session_end").show(),$("#session_end_button").focus())};
Games.Common.processFinalScore=function(){var a,b;a=statusModel.getScore();var c,d;statusModel.setDate();b=statusModel.getDateTime();c=statusModel.getDateString();d=statusModel.getTimeString();b="score="+a+"&time="+b+"&date_string="+c+"&time_string="+d;Modernizr.localstorage&&(c=statusModel.getHiScore(),a=c>a?c:a);statusModel.setHiScore(a);$("#score_text").html("Please wait . . . retrieving scores");ajaxUtilities.createXHR();a=ajaxUtilities.getXHR();ajaxUtilities.open("POST","php/get_scores.php");
a.onreadystatechange=ajaxUtilities.onChange;ajaxUtilities.send("POST",b)};
Games.Common.displayFinalScore=function(a){var b,c,d,e="",f="",g="",h="your score: "+statusModel.getScore(),i=statusModel.top_scores.length;if(a)for(a=0;a<i;a++)b=parseInt(statusModel.top_scores[a]),c=statusModel.top_date_strings[a],d=parseInt(statusModel.top_times[a]),b===statusModel.getScore()&&d===statusModel.getDateTime()?(e+='<span class="your_scores">'+(a+1)+".</span><br />",f+='<span class="your_scores">'+b+"*</span><br />",g+='<span class="your_scores">'+c+"</span><br />",h="* your score"):
(e+=a+1+".<br />",f+=b+"<br />",g+=c+"<br />");else for(a=0;a<10;a++)e+=a+1+".<br />",f+="unavailable<br />",g+="unavailable<br />";$("#score_display_frame").show();$("#main_menu_button").focus();$("#top_rank").html(e);$("#top_scores").html(f);$("#top_dates").html(g);$("#top_score_footer").html(h)};Games.Common.AjaxUtilities=function(){var a,b,c=!1;this.createXHR=function(){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};this.getXHR=function(){return a};this.open=function(b,e){try{a.open(b,e,!0)}catch(f){c=!1}};this.send=function(b,e){try{a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(e)}catch(f){c=!1}};this.onChange=function(){var d,e,f;if(a.readyState===4){if(a.status===200||a.statusText==="OK"){c=!0;try{b=a.responseXML;e=b.getElementsByTagName("score");
f=b.getElementsByTagName("time");ds=b.getElementsByTagName("date_string");ts=b.getElementsByTagName("time_string");for(d=0;d<e.length;d++)statusModel.top_scores[d]=e[d].childNodes[0].nodeValue,statusModel.top_times[d]=f[d].childNodes[0].nodeValue,statusModel.top_date_strings[d]=ds[d].childNodes[0].nodeValue,statusModel.top_time_strings[d]=ts[d].childNodes[0].nodeValue}catch(g){c=!1}}else c=!1;Games.Common.displayFinalScore(c);$("#main_menu_button").show()}}};Flash.ScaleDegree={};Games.Notation={};Games.Notation.Config=function(){this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;this.TREBLE_OFFSET=10;this.BASS_OFFSET=12;this.ALTO_OFFSET=11;this.TENOR_OFFSET=9;this.RANDOM_TB=4;this.RANDOM_AT=5;this.RANDOM_ALL=6;this.ENTER_KEY=13;this.ESC_KEY=27;this.UP_KEY=38;this.DOWN_KEY=40;this.KEY_C=65;this.KEY_CS=87;this.KEY_D=83;this.KEY_DS=69;this.KEY_E=68;this.KEY_F=70;this.KEY_FS=84;this.KEY_G=71;this.KEY_GS=89;this.KEY_A=72;this.KEY_AS=85;this.KEY_B=74;this.KEY_C2=75;this.SMALL="small";this.SMALL_W=
"small_w";this.NORMAL="normal";this.NORMAL_W="normal_w";this.MEDIUM="medium";this.MEDIUM_W="medium_w";this.LARGE="large";this.LARGE_W="large_w";this.HUGE="huge";this.HUGE_W="huge_w";this.BG_STAVE_LEFT=20;this.BG_STAVE_TOP=10;this.BG_STAVE_WIDTH=100;this.BG_LAYER_WIDTH=320;this.BG_LAYER_HEIGHT=200;this.FG_STAVE_TOP=10;this.NOTE_LAYER_LEFT=this.KS_LAYER_LEFT=this.CLEF_LAYER_LEFT=0;this.CLEF_LAYER_WIDTH=70;this.KS_LAYER_WIDTH=100;this.NOTE_LAYER_WIDTH=146;this.CLEF_TYPES=["treble","bass","alto","tenor"];
this.MIN_RANGE_INDEX=0;this.MAX_RANGE_INDEX=3;this.ACC_LEVELS=[5,6,19,20];this.KS_TIER_1=[7,14];this.KS_TIER_2=[21,30];this.KS_EASY_LEVELS=[7,8,11,12,21,22,25,26,29];this.KS_HARD_LEVELS=[9,10,13,14,23,24,27,28,30];this.EASY_KEYS=0;this.HARD_KEYS=1;this.KS_MIN=this.CF;this.KS_MAX=this.CS;this.KS_MAJOR=0;this.KS_MINOR=1;this.ACC_SINGLE=0;this.ACC_DOUBLE=1;this.ACC_ALL=2;this.ACC_SINGLE_NOT_C=3;this.ACC_ALL_NOT_C=4;this.ACC_NONE=-1;this.ACC_TYPE_C=0;this.ACC_TYPE_FLAT=-1;this.ACC_TYPE_SHARP=1;this.ACCIDENTAL_ON=
{single_acc:!1,double_acc:!1};this.C=7;this.CS=14;this.CF=0;this.D=9;this.DF=2;this.E=11;this.EF=4;this.F=6;this.FS=13;this.G=8;this.GF=1;this.A=10;this.AF=3;this.B=12;this.BF=5;this.KEY_SIGS="Cb,Gb,Db,Ab,Eb,Bb,F,C,G,D,A,E,B,F#,C#".split(",");this.KS_C_INDEX=7;this.KS_EASY=[this.C,this.G,this.F,this.D,this.BF,this.A,this.EF];this.KS_HARD=[this.E,this.AF,this.B,this.DF,this.FS,this.GF,this.CS,this.CF];this.KS_SEL_WIDTH=55;this.KS_SEL_HEIGHT=45};Games.Notation.NotationController=function(){this.backend=Vex.Flow.Renderer.Backends.CANVAS;if(!Modernizr.canvas)this.backend=Vex.Flow.Renderer.Backends.RAPHAEL;this.note_spacer=135};Games.Notation.NotationController.prototype.drawStaff=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();b=new Vex.Flow.Stave(b,c,d);a.setTransform(1,0,0,1,0,0);a.scale(e,e);b.setContext(a).draw(a,!1,!1);return b};
Games.Notation.NotationController.prototype.drawClef=function(a,b,c){var a=document.getElementById(a),d=(new Vex.Flow.Renderer(a,this.backend)).getContext();b.addClef(c);b.glyphs.length>1&&(b.glyphs[0]=b.glyphs[b.glyphs.length-1],b.glyphs.pop(b.glyphs.length-1),b.glyphs.pop(b.glyphs.length-1),d.clearRect(0,0,a.width,a.height));b.setContext(d).draw(d,!1,!1)};
Games.Notation.NotationController.prototype.drawNote=function(a,b,c,d,e,f){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();c=new Vex.Flow.StaveNote({keys:[c],duration:d,clef:b.clef});f&&c.addAccidental(0,new Vex.Flow.Accidental(f));b.setNoteStartX(this.note_spacer);Vex.Flow.Formatter.FormatAndDraw(a,b,[c],e);return c};
Games.Notation.NotationController.prototype.drawNotes=function(a,b,c,d){var a=document.getElementById(a),a=(new Vex.Flow.Renderer(a,this.backend)).getContext(),e=0,f,g,h=[];for(f=0;f<c.length;f++)g=new Vex.Flow.StaveNote({keys:c[f].note_names,duration:c[f].note_dur,clef:b.clef}),h[f]=g;for(f=0;f<b.glyphs.length;f++)e+=b.glyphs[f].getMetrics().width;Vex.Flow.Formatter.FormatAndDraw(a,b,h,d);return g};
Games.Notation.NotationController.prototype.addAccidental=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();c.addAccidental(d,new Vex.Flow.Accidental(e));b.setContext(a).draw(a,!1,!1)};Games.Notation.NotationController.prototype.hideNote=function(a,b){var c=document.getElementById(a),d=(new Vex.Flow.Renderer(c,this.backend)).getContext();d.clearRect(0,0,c.width,c.height);b.setNoteStartX(this.note_spacer);b.setContext(d).draw(d,!1,!1)};
Games.Notation.NotationController.prototype.drawKeySignature=function(a,b,c){var a=document.getElementById(a),d=(new Vex.Flow.Renderer(a,this.backend)).getContext();this.clearKeySignature(b);d.clearRect(0,0,a.width,a.height);b.addKeySignature(c).setContext(d).draw(d,!1,!1)};Games.Notation.NotationController.prototype.clearKeySignature=function(a){var b;for(b=a.glyphs.length-1;b>0;b--)a.glyphs.pop(b)};
Games.Notation.NotationController.prototype.drawTimeSignature=function(a,b,c){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();b.addTimeSignature(c).setContext(a).draw(a,!1,!1)};Games.Notation.NotationController.prototype.clearTimeSignature=function(a){var b,c;for(b=a.glyphs.length-1;b>=0;b--)c=a.glyphs[b].code,c==="v0"&&a.glyphs.pop(b)};Games.Notation.NotationController.prototype.getNoteValue=function(){return notationModel.getNoteValue()};
Games.Notation.NotationController.prototype.setRangeIndex=function(a){notationModel.setRangeIndex(a)};Games.Notation.NotationController.prototype.getRandomClefIndex=function(a,b){return notationModel.randomClefIndex(a,b)};Games.Notation.NotationController.prototype.getRandomKeySignature=function(){return notationModel.randomKeySignature()};Games.Notation.NotationModel=function(){var a=cfg.MIN_RANGE_INDEX,b=cfg.TREBLE,c=0,d=0,e=-1,f=-1,g=-1,h=cfg.C,i=cfg.KEY_SIGS[h],j=cfg.SINGLE_C,k=!1,l=cfg.ACC_TYPE_C,m=!1;this.getRangeIndex=function(){return a};this.setRangeIndex=function(b){if(b<cfg.MIN_RANGE_INDEX)a=cfg.MIN_RANGE_INDEX;a=b>cfg.MAX_RANGE_INDEX?cfg.MAX_RANGE_INDEX:b};this.getClefIndex=function(){return b};this.setClefIndex=function(a){c=b;b=a};this.getPrevClefIndex=function(){return c};this.setPrevClefIndex=function(a){c=a};this.getNoteIndex=
function(){return d};this.setNoteIndex=function(a){d=a>=0?a:0;d>6&&(d=6)};this.getOctave=function(){return e};this.setOctave=function(a){e=a};this.getNoteValue=function(){return f};this.setNoteValue=function(a){var c;c=Vex.Flow.keyProperties(a,cfg.CLEF_TYPES[b]);a=c.int_value%12;f=a};this.getKeySignatureLevel=function(){return g};this.setKeySignatureLevel=function(a){g=a};this.getKeySigIndex=function(){return h};this.setKeySigIndex=function(a){h=a};this.getKeySignature=function(){return i};this.setKeySignature=
function(a){i=cfg.KEY_SIGS[a]};this.updateKeySignature=function(a){h+=a;h=a<0?h>=this.KS_MIN_INDEX?h:this.KS_MIN_INDEX:h<=this.KS_MAX_INDEX?h:this.KS_MAX_INDEX;i=cfg.KEY_SIGS[h];this.convertNoteValue()};this.getAccidentalRange=function(){return j};this.setAccidentalRange=function(a){j=a};this.getAddAccidental=function(){return k};this.setAddAccidental=function(a){k=a};this.getAccidentalType=function(){return l};this.setAccidentalType=function(a){l=a};this.getAddKeySignature=function(){return m};this.setAddKeySignature=
function(a){m=a};this.clefIndexArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];this.clefIndexProperties={0:!0,1:!1,2:!1,3:!1};this.keysig_acc_type={sharp:"#",flat:"b"}};Games.Notation.NotationModel.prototype.convertNoteIndex=function(){var a=this.getNoteIndex(),b=this.getClefIndex(),c=this.getPrevClefIndex(),d=[0,2,1,6];this.setNoteIndex(Math.abs((a-(d[c]-d[b]))%7))};
Games.Notation.NotationModel.prototype.convertNoteValue=function(){notationModel.getClefIndex();var a=this.getNoteIndex(),b=Vex.Flow.integerToNoteLetter(a),c=this.checkOctaveRange();b+=Games.Notation.keySignatureAccidentals(this.getKeySignature(),a);this.setNoteValue(""+b+"/"+c)};
Games.Notation.NotationModel.prototype.checkOctaveRange=function(){var a=this.getOctave(),b=this.getClefIndex(),c=this.getRangeIndex(),d=this.getNoteIndex(),e=Games.Notation.noteRangeProperties(b),b=e.base_octave[c],f=e.upper_octave[c],g=e.base_index[c],c=e.upper_index[c];a<b&&(a=b);a===b&&d<g&&(a=b+1);a>f&&(a=f);a===f&&d>c&&(a=f-1);return a};Games.Notation.NotationModel.prototype.randomClefIndex=function(a,b){return this.clefIndexArray[Math.round(Math.random()*100)%a+b]};
Games.Notation.NotationModel.prototype.practiceClefIndex=function(){var a,b;for(a=0;a<4;a++)if(b=this.clefIndexProperties[a])return this.clefIndexArray[a];return null};
Games.Notation.NotationModel.prototype.randomAccidental=function(){var a=this.getAccidentalRange(),b=null,c=[null,"b","#","bb","##","n"],d=[null,"b","#","n"],e=[null,"bb","##"],f=c.length,g=d.length,h=e.length;this.getNoteIndex();this.getKeySignature();switch(a){case cfg.ACC_ALL:a=Math.round(Math.random()*1E3)%(f-1);b=c[a];break;case cfg.ACC_ALL_NOT_C:a=Math.round(Math.random()*1E3)%f;(b=c[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_SINGLE:a=Math.round(Math.random()*1E3)%(g-1);b=d[a];break;
case cfg.ACC_SINGLE_NOT_C:a=Math.round(Math.random()*1E3)%g;(b=d[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_DOUBLE:a=Math.round(Math.random()*1E3)%h,b=e[a]}return b};Games.Notation.NotationModel.prototype.filterAccidental=function(a){var b=this.getKeySignature(),c=this.getNoteIndex(),b=Games.Notation.keySignatureAccidentals(b,c);return a==="##"||a==="bb"?a:a==="n"?b!=""?a:null:b==""?a:null};
Games.Notation.NotationModel.prototype.randomKeySignature=function(){var a;this.getKeySignatureLevel()===cfg.EASY_KEYS?(a=cfg.KS_EASY.length,a=Math.round(Math.random()*1E3)%a,a=cfg.KS_EASY[a]):(a=cfg.KS_HARD.length,a=Math.round(Math.random()*1E3)%a,a=cfg.KS_HARD[a]);return a};
Games.Notation.NotationModel.prototype.getImgUrl=function(a){switch(a){case cfg.TREBLE:return"images/treble.png";case cfg.BASS:return"images/bass.png";case cfg.ALTO:return"images/c_clef.png";case cfg.TENOR:return"images/c_clef.png";default:return"images/treble.png"}};Games.Notation.NotationModel.prototype.getClefOffset=function(a){switch(a){case cfg.TREBLE:return cfg.TREBLE_OFFSET;case cfg.BASS:return cfg.BASS_OFFSET;case cfg.ALTO:return cfg.ALTO_OFFSET;case cfg.TENOR:return cfg.TENOR_OFFSET;default:return cfg.TREBLE_OFFSET}};Flash.ScaleDegree.AjaxUtilities=function(){var a,b,c=!1;this.createXHR=function(){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};this.getXHR=function(){return a};this.open=function(b,e){try{a.open(b,e,!0)}catch(f){c=!1}};this.send=function(b,e){try{a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(e)}catch(f){c=!1}};this.onChange=function(){var d,e,f;if(a.readyState===4){if(a.status===200||a.statusText==="OK"){c=!0;try{b=a.responseXML;
e=b.getElementsByTagName("score");f=b.getElementsByTagName("time");ds=b.getElementsByTagName("date_string");ts=b.getElementsByTagName("time_string");for(d=0;d<e.length;d++)statusModel.top_scores[d]=e[d].childNodes[0].nodeValue,statusModel.top_times[d]=f[d].childNodes[0].nodeValue,statusModel.top_date_strings[d]=ds[d].childNodes[0].nodeValue,statusModel.top_time_strings[d]=ts[d].childNodes[0].nodeValue}catch(g){c=!1}}else c=!1;gameController.displayFinalScore(c);$("#main_menu_button").show()}}};$(document).ready(function(){Modernizr.canvas?(cfg=new Games.Notation.Config,statusModel=new Flash.ScaleDegree.StatusModel,statusView=new Flash.ScaleDegree.StatusView,notationModel=new Games.Notation.NotationModel,notationController=new Games.Notation.NotationController(cfg.MIN_RANGE),gameController=new Flash.ScaleDegree.GameController,$("#menu_frame").show(),$("#play_button").click(function(){gameController.displayGame()}),$("#play_button").keydown(function(a){a=parseInt(a.keyCode);(a===cfg.UP_KEY||
a===cfg.DOWN_KEY)&&$("#instructions_button").focus()}),$("#instructions_button").click(function(){$("#menu_frame").hide();$("#instructions_frame").show();$("#back_button").focus()}),$("#instructions_button").keydown(function(a){a=parseInt(a.keyCode);(a===cfg.UP_KEY||a===cfg.DOWN_KEY)&&$("#play_button").focus()}),$("#back_button").click(function(){$("#instructions_frame").hide();$("#menu_frame").show();$("#play_button").focus()}),$("#session_start_button").click(function(){$("#session_frame").hide();
statusModel.setIsTimeout(!1);$("#game_frame").show();$("#staff_paper").show();gameController.startGame("#status_timer")}),$("#session_end_button").click(function(){$("#session_frame").hide();Games.Common.displaySummary();$("#sum_continue_button").focus()}),$(".input").click(function(){var a=$(this).attr("value");gameController.continueGame(a)}),$("#scores_button").click(function(){$("#session_frame").hide();Games.Common.processFinalScore()}),$("#sum_continue_button").click(function(){$("#summary_frame").hide();
$("#session_frame").hide();statusModel.getIsTimeout()?gameController.updateLevel():gameController.startGame("#timer")}),$("#sum_continue_button").keydown(function(a){a=a.keyCode;if(a===cfg.UP_KEY||a===cfg.DOWN_KEY)$(this).blur(),$("#quit_button").focus()}),$("#quit_button").click(function(){$("#summary_frame").hide();Games.Common.processFinalScore();Games.Common.removeLivesDisplay();$("#score_display_frame").show()}),$("#quit_button").keydown(function(a){a=a.keyCode;(a===cfg.UP_KEY||a===cfg.DOWN_KEY)&&
$("#sum_continue_button").focus()}),$("#main_menu_button").click(function(){$("#score_display_frame").hide();$("#main_menu_button").hide();gameController.init();$("#menu_frame").show();$("#play_button").focus()}),$("button").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:0.9})})):$("#nocanvas_frame").show()});Flash.ScaleDegree.GameController=function(){this.MAJOR=0;this.MINOR=1;this.BOTH=2;this.SCALE=1.3;this.clef_type="treble";this.ks_index=cfg.C;this.key_spec=cfg.KEY_SIGS[this.ks_index];this.noteSpec="C";this.noteDur="w";this.timeSig=Vex.Flow.TIME4_4;this.timeOut=25;this.prev_labels=["","",""];this.init()};
Flash.ScaleDegree.GameController.prototype.init=function(){statusModel.start(!1);statusModel.setIsTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setLevel(1);statusModel.setPoints(0);statusModel.setAttempts(0);statusModel.setScore(0);statusModel.setLives(statusModel.MAX_LIVES);statusModel.setMaxKeyIndex(statusModel.TIER_1);statusView.displayTime("#status_timer",0);notationModel.setKeySignature(this.ks_index);this.stave=notationController.drawStaff("staff_paper",10,15,250,this.SCALE);
notationController.drawClef("staff_paper",this.stave,this.clef_type);statusModel.setClef(this.clef_type);Games.Common.displayScore();return this};Flash.ScaleDegree.GameController.prototype.displayGame=function(){this.init();statusView.initLivesDisplay("game_lives",statusModel.MAX_LIVES);statusView.initHitDisplay("hit_light");$("#status_level_label").html("Level:");$("#status_level").html("1");Games.Common.displaySessionAlert(!0,!1,!1)};
Flash.ScaleDegree.GameController.prototype.startGame=function(a){statusModel.getStart()?this.stopGame():(statusModel.start(!0),this.keySpec=statusModel.getKeySpec(),this.noteSpec=statusModel.getNoteSpec(),this.displayButtonLabels(),notationController.drawClef("staff_paper",this.stave,this.clef_type),notationController.drawKeySignature("staff_paper",this.stave,this.keySpec),notationController.hideNote("staff_paper",this.stave),notationController.drawNote("staff_paper",this.stave,this.noteSpec,this.noteDur,
this.timeSig),this.startTimer(a,this.timeOut))};
Flash.ScaleDegree.GameController.prototype.displayButtonLabels=function(){var a,b;a=statusModel.getLevel()%6;var c,d=statusModel.getTempDegrees(),e;switch(a){case 1:case 2:c="num";break;case 3:case 4:c="solf";break;case 5:case 0:c="tech";break;default:c="num"}for(a=0;a<d.length;a++)e=d[a].solfege,label=c==="num"?d[a].number:c==="solf"?d[a].solfege:d[a].technical,b="#"+$("div.input_box button")[a].id,$(b).html(""+label),$(b).removeClass(this.prev_labels[a]),$(b).addClass(e),this.prev_labels[a]=e};
Flash.ScaleDegree.GameController.prototype.startTimer=function(a,b){var c,d=this;b<0?(clearTimeout(this.getT),statusModel.setIsTimeout(!0),this.stopGame()):c=setTimeout(function(){d.updateTimer(a,b,c)},1E3);statusView.displayTime(a,b);return this};Flash.ScaleDegree.GameController.prototype.updateTimer=function(a,b,c){statusModel.getStart()&&(b-=1,statusModel.setTime(b),statusModel.setTimeInterval(b),this.startTimer(a,b,c))};
Flash.ScaleDegree.GameController.prototype.continueGame=function(a){var b=statusModel.getStart();statusModel.getLevel();statusModel.setInputCode(parseInt(a));(a=statusModel.getMatch())?statusView.updateHitDisplay(!0):(statusView.updateHitDisplay(!1),statusModel.decLives(),statusModel.getLives(),statusView.updateLivesDisplay());if(b&&a)this.keySpec=statusModel.getKeySpec(),this.noteSpec=statusModel.getNoteSpec(),notationController.drawClef("staff_paper",this.stave,this.clef_type),notationController.drawKeySignature("staff_paper",
this.stave,this.keySpec),notationController.hideNote("staff_paper",this.stave),notationController.drawNote("staff_paper",this.stave,this.noteSpec,this.noteDur,this.timeSig),this.displayButtonLabels(),statusModel.addPoint(),statusModel.calculateScore();b&&(statusModel.addAttempt(),Games.Common.displayScore())};
Flash.ScaleDegree.GameController.prototype.stopGame=function(){var a,b;statusModel.start(!1);a=statusModel.isLevelAdvance();b=statusModel.getLives()>0?!1:!0;a&&(statusModel.advanceLevel(),statusModel.addBonus());Games.Common.displaySessionAlert(!1,b,a);return this};Flash.ScaleDegree.GameController.prototype.resetGame=function(){statusModel.setIsTimeout(!1);statusModel.setTimeInterval(this.timeOut);statusModel.setPoints(0);statusModel.setAttempts(0);this.clef_type="treble";Games.Common.displayScore()};
Flash.ScaleDegree.GameController.prototype.getStart=function(){return statusModel.getStart()};
Flash.ScaleDegree.GameController.prototype.updateLevel=function(){var a=statusModel.getLevel(),b,c,d=["treble","bass","alto","tenor"];statusModel.getIsTimeout()&&this.resetGame();if(a<25)this.clef_type=a%2===1?"treble":"bass",statusModel.setClef(this.clef_type);if(a>=25&&a<37)this.clef_type=a%2===1?"alto":"tenor",statusModel.setClef(this.clef_type);if(a>=37)c=Math.round(Math.random()*1E3)%4,this.clef_type=d[c],statusModel.setClef(this.clef_type);if(a<7)b=statusModel.TIER_1;if(a>=7&&a<13||a>=25&&a<
31)b=statusModel.TIER_2;if(a>=13&&a<19||a>=31&&a<37)b=statusModel.TIER_3;if(a>=19&&a<25||a>=37)b=statusModel.TIER_4;statusModel.setMaxKeyIndex(b);Games.Common.displayScore();Games.Common.displaySessionAlert(!0,!1,!1)};Flash.ScaleDegree.StatusModel=function(){this.MAX_LEVEL=38;this.TIER_1=2;this.TIER_2=6;this.TIER_3=10;this.TIER_4=14;this.MIN_ATTEMPTS=5;this.MIN_PERCENT=80;this.BONUS_INC=this.BONUS=10;this.BONUS_LEVEL=12;this.MAX_LIVES=5;this.bonus=this.level=this.score=this.attempts=this.points=0;this.lives=5;this.go=!1;this.timeInterval=this.TIMEOUT;this.isTimeOut=!1;this.value_code=this.input_code=0;this.clef="treble";this.current_ks_index=this.TIER_1;this.keyIndex=0;this.key_sigs={0:{spec:"C",majorName:"c_maj",
minorName:"a_min",degreeOffset:0},1:{spec:"G",majorName:"g_maj",minorName:"e_min",degreeOffset:4},2:{spec:"F",majorName:"f_maj",minorName:"d_min",degreeOffset:3},3:{spec:"D",majorName:"d_maj",minorName:"b_min",degreeOffset:1},4:{spec:"Bb",majorName:"bf_maj",minorName:"g_min",degreeOffset:6},5:{spec:"A",majorName:"a_maj",minorName:"fs_min",degreeOffset:5},6:{spec:"Eb",majorName:"ef_maj",minorName:"c_min",degreeOffset:2},7:{spec:"E",majorName:"e_maj",minorName:"cs_min",degreeOffset:2},8:{spec:"Ab",
majorName:"af_maj",minorName:"f_min",degreeOffset:5},9:{spec:"B",majorName:"b_maj",minorName:"gs_min",degreeOffset:6},10:{spec:"Db",majorName:"df_maj",minorName:"bf_min",degreeOffset:1},11:{spec:"F#",majorName:"fs_maj",minorName:"ds_min",degreeOffset:3},12:{spec:"Gb",majorName:"gf_maj",minorName:"ef_min",degreeOffset:4},13:{spec:"C#",majorName:"cs_maj",minorName:"as_min",degreeOffset:0},14:{spec:"Cb",majorName:"cf_maj",minorName:"af_min",degreeOffset:0}};this.scale_degrees={0:{number:1,solfege:"do",
technical:"tonic"},1:{number:2,solfege:"re",technical:"supertonic"},2:{number:3,solfege:"mi",technical:"mediant"},3:{number:4,solfege:"fa",technical:"subdominant"},4:{number:5,solfege:"sol",technical:"dominant"},5:{number:6,solfege:"la",technical:"submediant"},6:{number:7,solfege:"ti",technical:"leading tone"}};this.temp_sigs=[];this.temp_degrees=[];this.top_scores=[];this.top_times=[];this.top_date_strings=[];this.top_time_strings=[];this.hi_score=Modernizr.localstorage?(this.old_score=parseInt(localStorage.getItem("hiscore_degree")))?
this.old_score:0:0};Flash.ScaleDegree.StatusModel.prototype.getTime=function(){return this.time};Flash.ScaleDegree.StatusModel.prototype.setTime=function(a){this.time=a};Flash.ScaleDegree.StatusModel.prototype.setDate=function(){this.date=new Date;this.date_time=this.date.getTime()};Flash.ScaleDegree.StatusModel.prototype.getDateTime=function(){return this.date_time};
Flash.ScaleDegree.StatusModel.prototype.getDateString=function(){var a=""+(this.date.getMonth()+1),b=this.date.getDate()<10?"0"+this.date.getDate():this.date.getDate();return a+"-"+b+"-"+this.date.getFullYear()};Flash.ScaleDegree.StatusModel.prototype.getTimeString=function(){var a=""+this.date.getHours(),b=this.date.getMinutes()<10?"0"+this.date.getMinutes():this.date.getMinutes(),c=this.date.getSeconds()<10?"0"+this.date.getSeconds():this.date.getSeconds();return a+":"+b+":"+c};
Flash.ScaleDegree.StatusModel.prototype.addPoint=function(){this.points+=1};Flash.ScaleDegree.StatusModel.prototype.setPoints=function(a){this.points=a};Flash.ScaleDegree.StatusModel.prototype.getPoints=function(){return this.points};Flash.ScaleDegree.StatusModel.prototype.addAttempt=function(){this.attempts+=1};Flash.ScaleDegree.StatusModel.prototype.setAttempts=function(a){this.attempts=a};Flash.ScaleDegree.StatusModel.prototype.getAttempts=function(){return this.attempts};
Flash.ScaleDegree.StatusModel.prototype.getPercent=function(){return Math.floor(this.points/this.attempts*100)};Flash.ScaleDegree.StatusModel.prototype.calculateScore=function(){this.score+=this.points*this.level};Flash.ScaleDegree.StatusModel.prototype.addBonus=function(){this.bonus=this.BONUS*this.level;this.score+=this.bonus};Flash.ScaleDegree.StatusModel.prototype.getBonus=function(){return this.bonus};Flash.ScaleDegree.StatusModel.prototype.setScore=function(a){this.score=a};
Flash.ScaleDegree.StatusModel.prototype.getScore=function(){return this.score};Flash.ScaleDegree.StatusModel.prototype.getHiScore=function(){return this.hi_score};Flash.ScaleDegree.StatusModel.prototype.setHiScore=function(a){this.hi_score=a;Modernizr.localstorage&&localStorage.setItem("hiscore_degree",this.hi_score)};Flash.ScaleDegree.StatusModel.prototype.setLevel=function(a){this.level=a;this.level>this.BONUS_LEVEL&&(this.BONUS+=this.BONUS_INC)};
Flash.ScaleDegree.StatusModel.prototype.getLevel=function(){return this.level};Flash.ScaleDegree.StatusModel.prototype.advanceLevel=function(){this.setLevel(this.level<this.MAX_LEVEL?this.level+=1:this.MAX_LEVEL);return this};Flash.ScaleDegree.StatusModel.prototype.decLives=function(){this.lives-=1;if(this.lives<0)this.lives=0};Flash.ScaleDegree.StatusModel.prototype.setLives=function(a){this.lives=a};Flash.ScaleDegree.StatusModel.prototype.getLives=function(){return this.lives};
Flash.ScaleDegree.StatusModel.prototype.start=function(a){this.go=a};Flash.ScaleDegree.StatusModel.prototype.getStart=function(){return this.go};Flash.ScaleDegree.StatusModel.prototype.setTimeInterval=function(a){this.timeInterval=a};Flash.ScaleDegree.StatusModel.prototype.getTimeInterval=function(){return this.timeInterval};Flash.ScaleDegree.StatusModel.prototype.setIsTimeout=function(a){this.isTimeOut=a};Flash.ScaleDegree.StatusModel.prototype.getIsTimeout=function(){return this.isTimeOut};
Flash.ScaleDegree.StatusModel.prototype.getMaxKeyIndex=function(){return this.current_ks_index};Flash.ScaleDegree.StatusModel.prototype.setMaxKeyIndex=function(a){this.current_ks_index=a};
Flash.ScaleDegree.StatusModel.prototype.getKeySpec=function(){var a=[],b,c,d=this.getMaxKeyIndex();a[0]=this.key_sigs[0];for(b=1;b<=d;b++)c=Math.round(Math.random()*100)%(b+1),a[b]=a[c],a[c]=this.key_sigs[b];for(b=0;b<3;b++)this.temp_sigs[b]=a[b];c=Math.round(Math.random()*1E3)%3;this.keyIndex=this.temp_sigs[c].degreeOffset;return this.keySpec=this.temp_sigs[c].spec};Flash.ScaleDegree.StatusModel.prototype.getTempSigs=function(){return this.temp_sigs};
Flash.ScaleDegree.StatusModel.prototype.getNoteSpec=function(){var a=[],b,c,d=Math.round(Math.random()*1E3%4)+2;a[0]=this.scale_degrees[0];for(b=1;b<7;b++)c=Math.round(Math.random()*100)%(b+1),a[b]=a[c],a[c]=this.scale_degrees[b];for(b=0;b<3;b++)this.temp_degrees[b]=a[b];this.value_code=c=Math.round(Math.random()*1E3)%3;a=(this.temp_degrees[c].number-1+this.keyIndex)%7;switch(this.clef){case "treble":d<4&&(d=a<6?4:3);d>5&&(d=5);break;case "bass":d<3&&a<1&&(d=3);d>3&&(d=a>1?3:4);break;case "alto":d<
3&&(d=3);d>4&&a>0&&(d=4);break;case "tenor":d<3&&a<5&&(d=3),d>4&&(d=a<6?4:3)}return Vex.Flow.integerToNoteLetter(a)+"/"+d};Flash.ScaleDegree.StatusModel.prototype.getTempDegrees=function(){return this.temp_degrees};Flash.ScaleDegree.StatusModel.prototype.setInputCode=function(a){this.input_code=a};Flash.ScaleDegree.StatusModel.prototype.getMatch=function(){return this.input_code===this.value_code};
Flash.ScaleDegree.StatusModel.prototype.isLevelAdvance=function(){return this.getPercent()>=this.MIN_PERCENT&&this.getIsTimeout()&&this.getAttempts()>=this.MIN_ATTEMPTS?!0:!1};Flash.ScaleDegree.StatusModel.prototype.setClef=function(a){this.clef=a;return this};Flash.ScaleDegree.StatusModel.prototype.getClef=function(a){return this.clef=a};Flash.ScaleDegree.StatusView=function(){var a,b,c,d,e,f,g,h=[],i,j;this.initLivesDisplay=function(c,d){b=Raphael(c,60,20);for(a=0;a<d;a++)h[a]=b.circle(10*(a+1),5,4.5).attr({fill:"green",stroke:"#000"})};this.updateLivesDisplay=function(){i=h.length;i>0&&(h[i-1].remove(),h.pop())};this.removeLivesDisplay=function(){b.remove()};this.drawStatusBar=function(a,b,e,f){c=Raphael(a,b,e,f);d=c.rect(0,0,e,f);d.attr({stroke:"red",fill:"#202000"})};this.initHitDisplay=function(a){e=Raphael(a,0,0);f=e.path("M 5 18 L 17 30 L 33 2 L 17 23 Z").attr({stroke:"#447",
"stroke-width":1});g=e.path("M 5 5 L 35 35 M 35 5 L 5 35").attr({stroke:"#447","stroke-width":5});f.hide();g.hide()};this.removeHitDisplay=function(){e.remove();$(".hit_box").hide()};this.updateHitDisplay=function(a){a?(f.attr({stroke:"#0c2",fill:"#0c2"}),g.hide(),f.show()):(g.attr({stroke:"#f00"}),f.hide(),g.show());this.startHitTimer();$(".hit_box").show()};this.startHitTimer=function(){var a=this;j=setTimeout(function(){a.stopHitTimer()},600)};this.stopHitTimer=function(){f.hide();g.hide();$(".hit_box").hide();
clearTimeout(j)}};Flash.ScaleDegree.StatusView.prototype.displayInputLabels=function(a,b){var c,d,e,f=btn_array.length;for(c=0;c<f;c++)d=a[c],e=b[c],$(d).html(e)};Flash.ScaleDegree.StatusView.prototype.displayTime=function(a,b){var c="00:",d=b>=0?""+b:""+(b+1);b<10&&(c="00:0");$(a).html(c+d)};Flash.ScaleDegree.StatusView.prototype.displayLevel=function(a,b){var c;$(a).html(""+b)};Flash.ScaleDegree.StatusView.prototype.displayPoints=function(a,b,c){$(a).html(""+b+"/"+c)};
Flash.ScaleDegree.StatusView.prototype.displayPercent=function(a,b,c){b=""+(c>0?Math.round(b/c*100):0)+"%";$(a).html(b)};Flash.ScaleDegree.StatusView.prototype.displayScore=function(a,b){var c;$(a).html(""+b)};Flash.ScaleDegree.StatusView.prototype.displayHiScore=function(a,b){var c;$(a).html(""+b)};
