function Games(){};function Flash(){};Games.Common={};Games.Common.displayScore=function(){statusView.displayPoints("#status_points",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#status_percent",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#status_score",statusModel.getScore());statusView.displayLevel("#status_level",statusModel.getLevel());statusView.displayHiScore("#hi_score",statusModel.getHiScore())};
Games.Common.displaySummary=function(){$("#game_frame").hide();$("#staff_paper").hide();statusView.displayPoints("#point_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#percent_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#score_summary",statusModel.getScore());$("#time_summary_row").hide();$("#score_summary_row").show();$("#level_summary_row").show();$("#lives_summary_row").show();$("#next_level_row").show();$("#level_summary").html(""+
statusModel.getLevel());$("#lives_summary").html(""+statusModel.getLives());$("#summary_frame").show()};Games.Common.removeLivesDisplay=function(){statusView.removeLivesDisplay()};
Games.Common.displaySessionAlert=function(a,b,c){$("#menu_frame").hide();$("#instructions_frame").hide();$("#summary_frame").hide();$("#game_frame").hide();$("#staff_paper").hide();$("#menu_buttons").hide();$("#session_frame").show();$("#game_status_box").show();a&&!b?($("#session_start_header").html("Level "+statusModel.getLevel()),$("#session_end").hide(),$("#game_end").hide(),$("#session_start").show(),$("#session_start_button").focus()):b?($("#session_start").hide(),$("#session_end").hide(),$("#game_end").show(),
$("#scores_button").focus()):($("#session_start").hide(),$("#game_end").hide(),lives=statusModel.getLives(),lives_str=1<lives?" lives":" life",$("#lives").html(""+statusModel.getLives()+lives_str+" left"),c?($("#session_end_header").html("Good Job!"),$("#bonus").html("BONUS PTS<br/>"+statusModel.getBonus())):($("#session_end_header").html("Same Level"),$("#bonus").html("BONUS PTS<br/>0")),$("#session_end").show(),$("#session_end_button").focus())};
Games.Common.processFinalScore=function(){var a,b;a=statusModel.getScore();var c,d;statusModel.setDate();b=statusModel.getDateTime();c=statusModel.getDateString();d=statusModel.getTimeString();b="score="+a+"&time="+b+"&date_string="+c+"&time_string="+d;Modernizr.localstorage?(c=statusModel.getHiScore(),statusModel.setHiScore(c>a?c:a)):statusModel.setHiScore(a);$("#score_text").html("Please wait . . . retrieving scores");ajaxUtilities.createXHR();a=ajaxUtilities.getXHR();ajaxUtilities.open("POST",
"php/get_scores.php");a.onreadystatechange=ajaxUtilities.onChange;ajaxUtilities.send("POST",b)};
Games.Common.displayFinalScore=function(a){var b,c,d,e="",f="",g="",h="your score: "+statusModel.getScore(),k=statusModel.top_scores.length;if(a)for(a=0;a<k;a++)b=parseInt(statusModel.top_scores[a]),c=statusModel.top_date_strings[a],d=parseInt(statusModel.top_times[a]),b===statusModel.getScore()&&d===statusModel.getDateTime()?(e+='<span class="your_scores">'+(a+1)+".</span><br />",f+='<span class="your_scores">'+b+"*</span><br />",g+='<span class="your_scores">'+c+"</span><br />",h="* your score"):
(e+=a+1+".<br />",f+=b+"<br />",g+=c+"<br />");else for(a=0;10>a;a++)e+=a+1+".<br />",f+="unavailable<br />",g+="unavailable<br />";$("#score_display_frame").show();$("#main_menu_button").focus();$("#top_rank").html(e);$("#top_scores").html(f);$("#top_dates").html(g);$("#top_score_footer").html(h)};Games.Common.AjaxUtilities=function(){var a,b,c=!1;this.createXHR=function(){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};this.getXHR=function(){return a};this.open=function(b,e){try{a.open(b,e,!0)}catch(f){c=!1}};this.send=function(b,e){try{a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(e)}catch(f){c=!1}};this.onChange=function(){var d,e,f;if(4===a.readyState){if(200===a.status||"OK"===a.statusText){c=!0;try{for(b=a.responseXML,
e=b.getElementsByTagName("score"),f=b.getElementsByTagName("time"),ds=b.getElementsByTagName("date_string"),ts=b.getElementsByTagName("time_string"),d=0;d<e.length;d++)statusModel.top_scores[d]=e[d].childNodes[0].nodeValue,statusModel.top_times[d]=f[d].childNodes[0].nodeValue,statusModel.top_date_strings[d]=ds[d].childNodes[0].nodeValue,statusModel.top_time_strings[d]=ts[d].childNodes[0].nodeValue}catch(g){c=!1}}else c=!1;Games.Common.displayFinalScore(c);$("#main_menu_button").show()}}};Flash.Interval={};Flash.Interval.intervalProperties=function(a){return Flash.Interval.intervalProperties.table[a]};
Flash.Interval.intervalProperties.table={0:{size:2,quality:"d",label:"d2",halfsteps:0,bgcolor:"#F6F9ED",target:!1,rank:0},1:{size:2,quality:"m",label:"m2",halfsteps:1,bgcolor:"#ECF1EF",target:!1,rank:1},2:{size:2,quality:"M",label:"M2",halfsteps:2,bgcolor:"#FCF6CF",target:!1,rank:2},3:{size:2,quality:"A",label:"A2",halfsteps:3,bgcolor:"#FEEECD",target:!1,rank:3},4:{size:3,quality:"d",label:"d3",halfsteps:2,bgcolor:"#FEF1E9",target:!1,rank:4},5:{size:3,quality:"m",label:"m3",halfsteps:3,bgcolor:"#76EEC6",
target:!1,rank:5},6:{size:3,quality:"M",label:"M3",halfsteps:4,bgcolor:"#E0EEEE",target:!1,rank:6},7:{size:3,quality:"A",label:"A3",halfsteps:5,bgcolor:"#FFE4C4",target:!1,rank:7},8:{size:4,quality:"d",label:"d4",halfsteps:4,bgcolor:"#FFD39B",target:!1,rank:8},9:{size:4,quality:"p",label:"P4",halfsteps:5,bgcolor:"#8EE5EE",target:!1,rank:9},10:{size:4,quality:"A",label:"A4",halfsteps:6,bgcolor:"#EEE8CD",target:!1,rank:10},11:{size:5,quality:"d",label:"d5",halfsteps:6,bgcolor:"#FFB90F",target:!1,rank:11},
12:{size:5,quality:"p",label:"P5",halfsteps:7,bgcolor:"#BDB76B",target:!1,rank:12},13:{size:5,quality:"A",label:"A5",halfsteps:8,bgcolor:"#A2CD5A",target:!1,rank:13},14:{size:6,quality:"d",label:"d6",halfsteps:7,bgcolor:"#E9967A",target:!1,rank:14},15:{size:6,quality:"m",label:"m6",halfsteps:8,bgcolor:"#8DEEEE",target:!1,rank:15},16:{size:6,quality:"M",label:"M6",halfsteps:9,bgcolor:"#00BFFF",target:!1,rank:16},17:{size:6,quality:"A",label:"A6",halfsteps:10,bgcolor:"#EEC900",target:!1,rank:17},18:{size:7,
quality:"d",label:"d7",halfsteps:9,bgcolor:"#F0FFF0",target:!1,rank:18},19:{size:7,quality:"m",label:"m7",halfsteps:10,bgcolor:"#FFFFF0",target:!1,rank:19},20:{size:7,quality:"M",label:"M7",halfsteps:11,bgcolor:"#FFF68F",target:!1,rank:20},21:{size:7,quality:"A",label:"A7",halfsteps:12,bgcolor:"#CAE1FF",target:!1,rank:21},22:{size:8,quality:"p",label:"P8",halfsteps:12,bgcolor:"#FFE4E1",target:!1,rank:22}};
Flash.Interval.baseNote=function(a){base_notes="C F G D E A B C# CB DB EB F# GB AB BB".split(" ");return base_notes[a]};Flash.Interval.accidental=function(a,b,c){return Flash.Interval.acc_table[a][b][c]};
Flash.Interval.acc_table={CBB:{2:{d:"",m:"",M:"bb",A:"b"},3:{d:"",m:"",M:"b",A:"b"},4:{d:"",p:"bb",A:"b"},5:{d:"",p:"bb",A:"b"},6:{d:"",m:"",M:"bb",A:"b"},7:{d:"",m:"",M:"bb",A:"b"}},CB:{2:{d:"",m:"bb",M:"b",A:""},3:{d:"",m:"bb",M:"b",A:""},4:{d:"bb",p:"b",A:""},5:{d:"bb",p:"b",A:""},6:{d:"",m:"bb",M:"b",A:""},7:{d:"",m:"bb",M:"b",A:""}},C:{2:{d:"bb",m:"b",M:"",A:"#"},3:{d:"bb",m:"b",M:"",A:"#"},4:{d:"b",p:"",A:"#"},5:{d:"b",p:"",A:"#"},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"bb",m:"b",M:"",A:"#"}},"C#":{2:{d:"b",
m:"",M:"#",A:"##"},3:{d:"b",m:"",M:"#",A:"##"},4:{d:"",p:"#",A:"##"},5:{d:"",p:"#",A:"##"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"b",m:"",M:"#",A:"##"}},"C##":{2:{d:"",m:"#",M:"##",A:""},3:{d:"",m:"#",M:"##",A:""},4:{d:"#",p:"##",A:""},5:{d:"#",p:"##",A:""},6:{d:"",m:"#",M:"##",A:""},7:{d:"",m:"#",M:"##",A:""}},DBB:{2:{d:"",m:"",M:"bb",A:"b"},3:{d:"",m:"bb",M:"b",A:""},4:{d:"",p:"bb",A:"b"},5:{d:"",p:"bb",A:"b"},6:{d:"",m:"",M:"bb",A:"b"},7:{d:"",m:"bb",M:"b",A:""}},DB:{2:{d:"",m:"bb",M:"b",A:""},3:{d:"bb",
m:"b",M:"",A:"#"},4:{d:"bb",p:"b",A:""},5:{d:"bb",p:"b",A:""},6:{d:"",m:"bb",M:"b",A:""},7:{d:"bb",m:"b",M:"",A:"#"}},D:{2:{d:"bb",m:"b",M:"",A:"#"},3:{d:"b",m:"",M:"#",A:"##"},4:{d:"b",p:"",A:"#"},5:{d:"b",p:"",A:"#"},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"b",m:"",M:"#",A:"##"}},"D#":{2:{d:"b",m:"",M:"#",A:"##"},3:{d:"",m:"#",M:"##",A:""},4:{d:"",p:"#",A:"##"},5:{d:"",p:"#",A:"##"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"",m:"#",M:"##",A:""}},"D##":{2:{d:"",m:"#",M:"##",A:""},3:{d:"#",m:"##",M:"",A:""},4:{d:"#",
p:"##",A:""},5:{d:"#",p:"##",A:""},6:{d:"",m:"#",M:"##",A:""},7:{d:"#",m:"##",M:"",A:""}},EBB:{2:{d:"",m:"bb",M:"b",A:""},3:{d:"",m:"bb",M:"b",A:""},4:{d:"",p:"bb",A:"b"},5:{d:"",p:"bb",A:"b"},6:{d:"",m:"bb",M:"b",A:""},7:{d:"",m:"bb",M:"b",A:""}},EB:{2:{d:"bb",m:"b",M:"",A:"#"},3:{d:"bb",m:"b",M:"",A:"#"},4:{d:"bb",p:"b",A:""},5:{d:"bb",p:"b",A:""},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"bb",m:"b",M:"",A:"#"}},E:{2:{d:"b",m:"",M:"#",A:"##"},3:{d:"b",m:"",M:"#",A:"##"},4:{d:"b",p:"",A:"#"},5:{d:"b",p:"",
A:"#"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"b",m:"",M:"#",A:"##"}},"E#":{2:{d:"",m:"#",M:"##",A:""},3:{d:"",m:"#",M:"##",A:""},4:{d:"",p:"#",A:"##"},5:{d:"",p:"#",A:"##"},6:{d:"",m:"#",M:"##",A:""},7:{d:"",m:"#",M:"##",A:""}},"E##":{2:{d:"#",m:"##",M:"",A:""},3:{d:"#",m:"##",M:"",A:""},4:{d:"#",p:"##",A:""},5:{d:"#",p:"##",A:""},6:{d:"#",m:"##",M:"",A:""},7:{d:"#",m:"##",M:"",A:""}},FB:{2:{d:"",m:"bb",M:"b",A:""},3:{d:"",m:"bb",M:"b",A:""},4:{d:"",p:"bb",A:"b"},5:{d:"bb",p:"b",A:""},6:{d:"",m:"bb",M:"b",
A:""},7:{d:"",m:"bb",M:"b",A:""}},F:{2:{d:"bb",m:"b",M:"",A:"#"},3:{d:"bb",m:"b",M:"",A:"#"},4:{d:"bb",p:"b",A:""},5:{d:"b",p:"",A:"#"},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"bb",m:"b",M:"",A:"#"}},"F#":{2:{d:"b",m:"",M:"#",A:"##"},3:{d:"b",m:"",M:"#",A:"##"},4:{d:"b",p:"",A:"#"},5:{d:"",p:"#",A:"##"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"b",m:"",M:"#",A:"##"}},GB:{2:{d:"",m:"bb",M:"b",A:""},3:{d:"",m:"bb",M:"b",A:""},4:{d:"bb",p:"b",A:""},5:{d:"bb",p:"b",A:""},6:{d:"",m:"bb",M:"b",A:""},7:{d:"bb",m:"b",M:"",
A:"#"}},G:{2:{d:"bb",m:"b",M:"",A:"#"},3:{d:"bb",m:"b",M:"",A:"#"},4:{d:"b",p:"",A:"#"},5:{d:"b",p:"",A:"#"},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"b",m:"",M:"#",A:"##"}},"G#":{2:{d:"b",m:"",M:"#",A:"##"},3:{d:"b",m:"",M:"#",A:"##"},4:{d:"",p:"#",A:"##"},5:{d:"",p:"#",A:"##"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"",m:"#",M:"##",A:""}},AB:{2:{d:"",m:"bb",M:"b",A:""},3:{d:"bb",m:"b",M:"",A:"#"},4:{d:"bb",p:"b",A:""},5:{d:"bb",p:"b",A:""},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"bb",m:"b",M:"",A:"#"}},A:{2:{d:"bb",
m:"b",M:"",A:"#"},3:{d:"b",m:"",M:"#",A:"##"},4:{d:"b",p:"",A:"#"},5:{d:"b",p:"",A:"#"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"b",m:"",M:"#",A:"##"}},"A#":{2:{d:"b",m:"",M:"#",A:"##"},3:{d:"",m:"#",M:"##",A:""},4:{d:"",p:"#",A:"##"},5:{d:"",p:"#",A:"##"},6:{d:"",m:"#",M:"##",A:""},7:{d:"",m:"#",M:"##",A:""}},BB:{2:{d:"bb",m:"b",M:"",A:"#"},3:{d:"bb",m:"b",M:"",A:"#"},4:{d:"bb",p:"b",A:""},5:{d:"b",p:"",A:"#"},6:{d:"bb",m:"b",M:"",A:"#"},7:{d:"bb",m:"b",M:"",A:"#"}},B:{2:{d:"b",m:"",M:"#",A:"##"},3:{d:"b",
m:"",M:"#",A:"##"},4:{d:"b",p:"",A:"#"},5:{d:"",p:"#",A:"##"},6:{d:"b",m:"",M:"#",A:"##"},7:{d:"b",m:"",M:"#",A:"##"}},"B#":{2:{d:"",m:"#",M:"##",A:""},3:{d:"",m:"#",M:"##",A:""},4:{d:"",p:"#",A:"##"},5:{d:"#",p:"##",A:""},6:{d:"",m:"#",M:"##",A:""},7:{d:"",m:"#",M:"##",A:""}}};
Flash.Interval.intervalSoundNameProperties=function(a){var b;switch(a){case "C":case "DBB":case "B#":b=0;break;case "D":case "EBB":case "C##":b=1;break;case "E":case "FB":case "D##":b=2;break;case "F":case "GBB":case "E#":b=3;break;case "G":case "ABB":case "F##":b=4;break;case "A":case "BBB":case "G##":b=5;break;case "B":case "CB":case "A##":b=6;break;case "C#":case "DB":case "B##":b=7;break;case "D#":case "EB":case "FBB":b=8;break;case "F#":case "GB":case "E##":b=9;break;case "G#":case "AB":b=10;
break;case "A#":case "BB":case "CBB":b=11}return Flash.Interval.intervalSoundNameProperties.table.names[b]};Flash.Interval.intervalSoundNameProperties.table={names:{0:{name:"C",offset:-2},1:{name:"D",offset:7},2:{name:"E",offset:15},3:{name:"F",offset:19},4:{name:"G",offset:27},5:{name:"A",offset:35},6:{name:"B",offset:43},7:{name:"Cs",offset:3},8:{name:"Ds",offset:11},9:{name:"Fs",offset:23},10:{name:"Gs",offset:31},11:{name:"As",offset:39}},length:12};
Flash.Interval.intervalSounds=function(){for(var a=[],b=0;b<Flash.Interval.intervalSounds.table.length;b++)a[b]=Flash.Interval.intervalSounds.table[b];return a};
Flash.Interval.intervalSounds.table={sounds:{0:{name:"C2",sound:null},1:{name:"C3",sound:null},2:{name:"C4",sound:null},3:{name:"C5",sound:null},4:{name:"C6",sound:null},5:{name:"Cs2",sound:null},6:{name:"Cs3",sound:null},7:{name:"Cs4",sound:null},8:{name:"Cs5",sound:null},9:{name:"D2",sound:null},10:{name:"D3",sound:null},11:{name:"D4",sound:null},12:{name:"D5",sound:null},13:{name:"Ds2",sound:null},14:{name:"Ds3",sound:null},15:{name:"Ds4",sound:null},16:{name:"Ds5",sound:null},17:{name:"E2",sound:null},
18:{name:"E3",sound:null},19:{name:"E4",sound:null},20:{name:"E5",sound:null},21:{name:"F2",sound:null},22:{name:"F3",sound:null},23:{name:"F4",sound:null},24:{name:"F5",sound:null},25:{name:"Fs2",sound:null},26:{name:"Fs3",sound:null},27:{name:"Fs4",sound:null},28:{name:"Fs5",sound:null},29:{name:"G2",sound:null},30:{name:"G3",sound:null},31:{name:"G4",sound:null},32:{name:"G5",sound:null},33:{name:"Gs2",sound:null},34:{name:"Gs3",sound:null},35:{name:"Gs4",sound:null},36:{name:"Gs5",sound:null},
37:{name:"A2",sound:null},38:{name:"A3",sound:null},39:{name:"A4",sound:null},40:{name:"A5",sound:null},41:{name:"As2",sound:null},42:{name:"As3",sound:null},43:{name:"As4",sound:null},44:{name:"As5",sound:null},45:{name:"B2",sound:null},46:{name:"B3",sound:null},47:{name:"B4",sound:null},48:{name:"B5",sound:null}},length:49};Games.Audio={};Games.Audio.Notes={};Games.Notation={};Games.Notation.Config=function(){this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;this.TREBLE_OFFSET=10;this.BASS_OFFSET=12;this.ALTO_OFFSET=11;this.TENOR_OFFSET=9;this.RANDOM_TB=4;this.RANDOM_AT=5;this.RANDOM_ALL=6;this.ENTER_KEY=13;this.ESC_KEY=27;this.UP_KEY=38;this.DOWN_KEY=40;this.KEY_C=65;this.KEY_CS=87;this.KEY_D=83;this.KEY_DS=69;this.KEY_E=68;this.KEY_F=70;this.KEY_FS=84;this.KEY_G=71;this.KEY_GS=89;this.KEY_A=72;this.KEY_AS=85;this.KEY_B=74;this.KEY_C2=75;this.SMALL="small";this.SMALL_W=
"small_w";this.NORMAL="normal";this.NORMAL_W="normal_w";this.MEDIUM="medium";this.MEDIUM_W="medium_w";this.LARGE="large";this.LARGE_W="large_w";this.HUGE="huge";this.HUGE_W="huge_w";this.BG_STAVE_LEFT=20;this.BG_STAVE_TOP=10;this.BG_STAVE_WIDTH=100;this.BG_LAYER_WIDTH=320;this.BG_LAYER_HEIGHT=200;this.FG_STAVE_TOP=10;this.NOTE_LAYER_LEFT=this.KS_LAYER_LEFT=this.CLEF_LAYER_LEFT=0;this.CLEF_LAYER_WIDTH=70;this.KS_LAYER_WIDTH=100;this.NOTE_LAYER_WIDTH=146;this.CLEF_TYPES=["treble","bass","alto","tenor"];
this.MIN_RANGE_INDEX=0;this.MAX_RANGE_INDEX=3;this.ACC_LEVELS=[5,6,19,20];this.KS_TIER_1=[7,14];this.KS_TIER_2=[21,30];this.KS_EASY_LEVELS=[7,8,11,12,21,22,25,26,29];this.KS_HARD_LEVELS=[9,10,13,14,23,24,27,28,30];this.EASY_KEYS=0;this.HARD_KEYS=1;this.KS_MIN=this.CF;this.KS_MAX=this.CS;this.KS_MAJOR=0;this.KS_MINOR=1;this.ACC_SINGLE=0;this.ACC_DOUBLE=1;this.ACC_ALL=2;this.ACC_SINGLE_NOT_C=3;this.ACC_ALL_NOT_C=4;this.ACC_NONE=-1;this.ACC_TYPE_C=0;this.ACC_TYPE_FLAT=-1;this.ACC_TYPE_SHARP=1;this.ACCIDENTAL_ON=
{single_acc:!1,double_acc:!1};this.C=7;this.CS=14;this.CF=0;this.D=9;this.DF=2;this.E=11;this.EF=4;this.F=6;this.FS=13;this.G=8;this.GF=1;this.A=10;this.AF=3;this.B=12;this.BF=5;this.KEY_SIGS="Cb Gb Db Ab Eb Bb F C G D A E B F# C#".split(" ");this.KS_C_INDEX=7;this.KS_EASY=[this.C,this.G,this.F,this.D,this.BF,this.A,this.EF];this.KS_HARD=[this.E,this.AF,this.B,this.DF,this.FS,this.GF,this.CS,this.CF];this.KS_SEL_WIDTH=55;this.KS_SEL_HEIGHT=45};Games.Notation.NotationController=function(){this.backend=Vex.Flow.Renderer.Backends.CANVAS;Modernizr.canvas||(this.backend=Vex.Flow.Renderer.Backends.RAPHAEL);this.note_spacer=120};Games.Notation.NotationController.prototype.drawStaff=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();b=new Vex.Flow.Stave(b,c,d);a.setTransform(1,0,0,1,0,0);a.scale(e,e);b.setContext(a).draw(a,!1,!1);return b};
Games.Notation.NotationController.prototype.drawClef=function(a,b,c){a=document.getElementById(a);var d=(new Vex.Flow.Renderer(a,this.backend)).getContext();b.addClef(c);1<b.glyphs.length&&(b.glyphs[0]=b.glyphs[b.glyphs.length-1],b.glyphs.pop(b.glyphs.length-1),b.glyphs.pop(b.glyphs.length-1),d.clearRect(0,0,a.width,a.height));b.setContext(d).draw(d,!1,!1)};
Games.Notation.NotationController.prototype.drawNote=function(a,b,c,d,e,f,g){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();c=new Vex.Flow.StaveNote({keys:[c],duration:d,clef:b.clef});g&&c.addAccidental(0,new Vex.Flow.Accidental(g));b.setNoteStartX(f);this.note_spacer=f;Vex.Flow.Formatter.FormatAndDraw(a,b,[c],e);return c};
Games.Notation.NotationController.prototype.drawNotes=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();var f,g,h,k=[],l=[],m=[];for(f=0;f<c.length;f++){for(g=0;g<c[f].note_names.length;g++)k[g]=c[f].note_names[g],l[g]=c[f].accidentals[g];h=new Vex.Flow.StaveNote({keys:k,duration:c[f].note_dur,clef:b.clef});for(g=0;g<c[f].note_names.length;g++)l[g]&&h.addAccidental(g,new Vex.Flow.Accidental(l[g]));m[f]=h}b.setNoteStartX(e);Vex.Flow.Formatter.FormatAndDraw(a,
b,m,d);return h};Games.Notation.NotationController.prototype.addAccidental=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();c.addAccidental(d,new Vex.Flow.Accidental(e));b.setContext(a).draw(a,!1,!1)};
Games.Notation.NotationController.prototype.hideNote=function(a,b){var c=document.getElementById(a),d=(new Vex.Flow.Renderer(c,this.backend)).getContext();d.clearRect(0,0,c.width,c.height);b.setNoteStartX(this.note_spacer);b.setContext(d).draw(d,!1,!1)};
Games.Notation.NotationController.prototype.drawKeySignature=function(a,b,c){a=document.getElementById(a);var d=(new Vex.Flow.Renderer(a,this.backend)).getContext();this.clearKeySignature(b);d.clearRect(0,0,a.width,a.height);b.addKeySignature(c).setContext(d).draw(d,!1,!1)};Games.Notation.NotationController.prototype.clearKeySignature=function(a){var b;for(b=a.glyphs.length-1;0<b;b--)a.glyphs.pop(b)};
Games.Notation.NotationController.prototype.drawTimeSignature=function(a,b,c){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();b.addTimeSignature(c).setContext(a).draw(a,!1,!1)};Games.Notation.NotationController.prototype.clearTimeSignature=function(a){var b,c;for(b=a.glyphs.length-1;0<=b;b--)c=a.glyphs[b].code,"v0"===c&&a.glyphs.pop(b)};Games.Notation.NotationController.prototype.getNoteValue=function(){return notationModel.getNoteValue()};
Games.Notation.NotationController.prototype.setRangeIndex=function(a){notationModel.setRangeIndex(a)};Games.Notation.NotationController.prototype.getRandomClefIndex=function(a,b){return notationModel.randomClefIndex(a,b)};Games.Notation.NotationController.prototype.getRandomKeySignature=function(){return notationModel.randomKeySignature()};Games.Notation.NotationModel=function(){var a=cfg.MIN_RANGE_INDEX,b=cfg.TREBLE,c=0,d=0,e=-1,f=-1,g=-1,h=cfg.C,k=cfg.KEY_SIGS[h],l=cfg.SINGLE_C,m=!1,n=cfg.ACC_TYPE_C,p=!1;this.getRangeIndex=function(){return a};this.setRangeIndex=function(b){b<cfg.MIN_RANGE_INDEX&&(a=cfg.MIN_RANGE_INDEX);a=b>cfg.MAX_RANGE_INDEX?cfg.MAX_RANGE_INDEX:b};this.getClefIndex=function(){return b};this.setClefIndex=function(a){c=b;b=a};this.getPrevClefIndex=function(){return c};this.setPrevClefIndex=function(a){c=a};this.getNoteIndex=
function(){return d};this.setNoteIndex=function(a){d=0<=a?a:0;6<d&&(d=6)};this.getOctave=function(){return e};this.setOctave=function(a){e=a};this.getNoteValue=function(){return f};this.setNoteValue=function(a){f=Vex.Flow.keyProperties(a,cfg.CLEF_TYPES[b]).int_value%12};this.getKeySignatureLevel=function(){return g};this.setKeySignatureLevel=function(a){g=a};this.getKeySigIndex=function(){return h};this.setKeySigIndex=function(a){h=a};this.getKeySignature=function(){return k};this.setKeySignature=
function(a){k=cfg.KEY_SIGS[a]};this.updateKeySignature=function(a){h+=a;h=0>a?h>=this.KS_MIN_INDEX?h:this.KS_MIN_INDEX:h<=this.KS_MAX_INDEX?h:this.KS_MAX_INDEX;k=cfg.KEY_SIGS[h];this.convertNoteValue()};this.getAccidentalRange=function(){return l};this.setAccidentalRange=function(a){l=a};this.getAddAccidental=function(){return m};this.setAddAccidental=function(a){m=a};this.getAccidentalType=function(){return n};this.setAccidentalType=function(a){n=a};this.getAddKeySignature=function(){return p};this.setAddKeySignature=
function(a){p=a};this.clefIndexArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];this.clefIndexProperties={0:!0,1:!1,2:!1,3:!1};this.keysig_acc_type={sharp:"#",flat:"b"}};Games.Notation.NotationModel.prototype.convertNoteIndex=function(){var a=this.getNoteIndex(),b=this.getClefIndex(),c=this.getPrevClefIndex(),d=[0,2,1,6];this.setNoteIndex(Math.abs((a-(d[c]-d[b]))%7))};
Games.Notation.NotationModel.prototype.convertNoteValue=function(){notationModel.getClefIndex();var a=this.getNoteIndex(),b=Vex.Flow.integerToNoteLetter(a),c=this.checkOctaveRange(),b=b+Games.Notation.keySignatureAccidentals(this.getKeySignature(),a);this.setNoteValue(""+b+"/"+c)};
Games.Notation.NotationModel.prototype.checkOctaveRange=function(){var a=this.getOctave(),b=this.getClefIndex(),c=this.getRangeIndex(),d=this.getNoteIndex(),e=Games.Notation.noteRangeProperties(b),b=e.base_octave[c],f=e.upper_octave[c],g=e.base_index[c],c=e.upper_index[c];a<b&&(a=b);a===b&&d<g&&(a=b+1);a>f&&(a=f);a===f&&d>c&&(a=f-1);return a};Games.Notation.NotationModel.prototype.randomClefIndex=function(a,b){return this.clefIndexArray[Math.round(100*Math.random())%a+b]};
Games.Notation.NotationModel.prototype.practiceClefIndex=function(){var a,b;for(a=0;4>a;a++)if(b=this.clefIndexProperties[a])return this.clefIndexArray[a];return null};
Games.Notation.NotationModel.prototype.randomAccidental=function(){var a=this.getAccidentalRange(),b=null,c=[null,"b","#","bb","##","n"],d=[null,"b","#","n"],e=[null,"bb","##"],f=c.length,g=d.length,h=e.length;this.getNoteIndex();this.getKeySignature();switch(a){case cfg.ACC_ALL:a=Math.round(1E3*Math.random())%(f-1);b=c[a];break;case cfg.ACC_ALL_NOT_C:a=Math.round(1E3*Math.random())%f;(b=c[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_SINGLE:a=Math.round(1E3*Math.random())%(g-1);b=d[a];break;
case cfg.ACC_SINGLE_NOT_C:a=Math.round(1E3*Math.random())%g;(b=d[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_DOUBLE:a=Math.round(1E3*Math.random())%h,b=e[a]}return b};Games.Notation.NotationModel.prototype.filterAccidental=function(a){var b=this.getKeySignature(),c=this.getNoteIndex(),b=Games.Notation.keySignatureAccidentals(b,c);return"##"===a||"bb"===a?a:"n"===a?""!=b?a:null:""==b?a:null};
Games.Notation.NotationModel.prototype.randomKeySignature=function(){var a;this.getKeySignatureLevel()===cfg.EASY_KEYS?(a=cfg.KS_EASY.length,a=Math.round(1E3*Math.random())%a,a=cfg.KS_EASY[a]):(a=cfg.KS_HARD.length,a=Math.round(1E3*Math.random())%a,a=cfg.KS_HARD[a]);return a};
Games.Notation.NotationModel.prototype.getImgUrl=function(a){switch(a){case cfg.TREBLE:return"images/treble.png";case cfg.BASS:return"images/bass.png";case cfg.ALTO:return"images/c_clef.png";case cfg.TENOR:return"images/c_clef.png";default:return"images/treble.png"}};Games.Notation.NotationModel.prototype.getClefOffset=function(a){switch(a){case cfg.TREBLE:return cfg.TREBLE_OFFSET;case cfg.BASS:return cfg.BASS_OFFSET;case cfg.ALTO:return cfg.ALTO_OFFSET;case cfg.TENOR:return cfg.TENOR_OFFSET;default:return cfg.TREBLE_OFFSET}};$(document).ready(function(){Modernizr.canvas?(cfg=new Games.Notation.Config,statusModel=new Flash.Interval.StatusModel,statusView=new Flash.Interval.StatusView,notationModel=new Games.Notation.NotationModel,notationController=new Games.Notation.NotationController(cfg.MIN_RANGE),gameController=new Flash.Interval.GameController,$("#menu_frame").show(),$("#play_button").click(function(){gameController.displayGame()}),$("#play_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#show_top_scores_button").focus();
a===cfg.DOWN_KEY&&$("#instructions_button").focus()}),$("#instructions_button").click(function(){$("#menu_frame").hide();$("#instructions_frame").show();$("#back_button").focus()}),$("#instructions_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#play_button").focus();a===cfg.DOWN_KEY&&$("#show_top_scores_button").focus()}),$("#back_button").click(function(){$("#instructions_frame").hide();$("#menu_frame").show();$("#play_button").focus()}),$("#show_top_scores_button").click(function(){Games.Common.processFinalScore()}),
$("#show_top_scores_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#instructions_button").focus();a===cfg.DOWN_KEY&&$("#play_button").focus()}),$("#session_start_button").click(function(){$("#session_frame").hide();statusModel.setIsTimeout(!1);$("#game_frame").show();$("#staff_paper").show();gameController.startGame()}),$("#session_end_button").click(function(){$("#session_frame").hide();Games.Common.displaySummary();$("#sum_continue_button").focus()}),$(".input").click(function(){var a=
$(this).attr("value");gameController.continueGame(a)}),$("#scores_button").click(function(){$("#session_frame").hide();Games.Common.processFinalScore()}),$("#sum_continue_button").click(function(){$("#summary_frame").hide();$("#session_frame").hide();gameController.updateLevel()}),$("#sum_continue_button").keydown(function(a){a=a.keyCode;if(a===cfg.UP_KEY||a===cfg.DOWN_KEY)$(this).blur(),$("#quit_button").focus()}),$("#quit_button").click(function(){$("#summary_frame").hide();Games.Common.processFinalScore();
Games.Common.removeLivesDisplay();$("#score_display_frame").show()}),$("#quit_button").keydown(function(a){a=a.keyCode;a!==cfg.UP_KEY&&a!==cfg.DOWN_KEY||$("#sum_continue_button").focus()}),$("#main_menu_button").click(function(){$("#score_display_frame").hide();$("#main_menu_button").hide();gameController.init();$("#menu_frame").show();$("#play_button").focus()}),$("button").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:.9})})):$("#nocanvas_frame").show()});Flash.Interval.GameController=function(){this.MAJOR=0;this.MINOR=1;this.BOTH=2;this.SCALE=1.3;this.SESSION_MAX=12;this.session_count=0;this.clef_type="treble";this.intervalNoteSpec=this.baseNoteSpec="";this.interval_mode=0;this.noteDur="w";this.timeSig=Vex.Flow.TIME4_4;this.startx=115;this.timeOut=10;this.init()};
Flash.Interval.GameController.prototype.init=function(){statusModel.setStart(!1);statusModel.setIsTimeout(!1);statusModel.setTimeInterval(this.timeOut);statusModel.setLevel(1);statusModel.setPoints(0);statusModel.setAttempts(0);statusModel.setScore(0);this.session_count=0;$(".listen_box").hide();statusModel.setLives(statusModel.MAX_LIVES);this.startx=115;this.stave=notationController.drawStaff("staff_paper",10,15,250,this.SCALE);notationController.drawClef("staff_paper",this.stave,this.clef_type);
statusModel.setClef(this.clef_type);Games.Common.displayScore();return this};Flash.Interval.GameController.prototype.displayGame=function(){this.init();statusView.initLivesDisplay("game_lives",statusModel.MAX_LIVES);statusView.initHitDisplay("hit_light");$("#status_level_label").html("Level:");$("#status_level").html("1");Games.Common.displaySessionAlert(!0,!1,!1)};
Flash.Interval.GameController.prototype.startGame=function(){var a=statusModel.getStart(),b;console.log("start: "+a);$(".listen_box").hide();a?this.stopGame():(statusModel.setStart(!0),statusModel.setPoints(0),statusModel.setAttempts(0),this.session_count=0,this.baseNoteProps=statusModel.getBaseNoteProperties(statusModel.getLevel()),this.baseNoteSpec=this.baseNoteProps.key+"/"+this.baseNoteProps.octave,this.intervalProps=statusModel.getRandomIntervalProperties(statusModel.getLevel()),a=this.intervalProps.size,
b=this.intervalProps.quality,"B"===this.baseNoteSpec[1]&&"E"!==this.baseNoteSpec[0]&&4!==a&&5!==a&&"d"===b&&(this.intervalProps=statusModel.getAltIntervalProperties()),"B"===this.baseNoteSpec[1]&&"F"===this.baseNoteSpec[0]&&4===a&&"d"===b&&(this.intervalProps=statusModel.getAltIntervalProperties()),"C"!==this.baseNoteSpec[0]&&"F"!==this.baseNoteSpec[0]&&"#"===this.baseNoteSpec[1]&&4!==a&&5!==a&&"A"===b&&(this.intervalProps=statusModel.getAltIntervalProperties()),"B"===this.baseNoteSpec[0]&&"#"===
this.baseNoteSpec[1]&&5===a&&"A"===b&&(this.intervalProps=statusModel.getAltIntervalProperties()),this.intervalNoteSpec=statusModel.getIntervalNoteSpec(this.baseNoteSpec,this.intervalProps.size,this.intervalProps.quality,this.clef_type),this.intervalNoteProps=Vex.Flow.keyProperties(this.intervalNoteSpec),a={0:{note_names:[this.baseNoteSpec,this.intervalNoteSpec],accidentals:[this.baseNoteProps.accidental,this.intervalNoteProps.accidental],note_dur:"w"},length:1},this.displayButtonLabels(),notationController.drawClef("staff_paper",
this.stave,this.clef_type),notationController.hideNote("staff_paper",this.stave),notationController.drawNotes("staff_paper",this.stave,a,this.timeSig,this.startx),this.interval_mode=1,this.session_count+=1)};
Flash.Interval.GameController.prototype.displayButtonLabels=function(){var a,b,c,d=statusModel.getTempIntervalProperties(),e=d.length;for(a=0;a<e-1;a++)for(b=a+1;b<e;b++)d[a].label===d[b].label&&(!1===d[a].target?d[a]=statusModel.getAltIntervalProperties():d[b]=statusModel.getAltIntervalProperties());if(2===this.interval_mode)for(a=0;a<e-1;a++)for(b=a+1;b<e;b++)d[a].halfsteps===d[b].halfsteps&&(!1===d[a].target?d[a]=statusModel.getAltSoundProperties():d[b]=statusModel.getAltSoundProperties());for(b=
1;b<e;b++){c=d[b];for(a=b-1;0<=a&&d[a].rank>c.rank;)d[a+1]=d[a],--a;d[a+1]=c}for(a=0;a<e;a++)b=d[a].label,bg=d[a].bgcolor,id="#"+$("div.input_box button")[a].id,$(id).html(""+b),$(id).css("background-color",bg),!0===d[a].target&&(statusModel.value_code=a)};
Flash.Interval.GameController.prototype.continueGame=function(a){var b=this,c=statusModel.getStart(),d=statusModel.getLevel(),e,f,g;statusModel.setInputCode(parseInt(a));(a=statusModel.getMatch())?(statusView.updateHitDisplay(!0),$(".listen_box").hide(),this.session_count+=1,console.log("session_count: "+this.session_count+", SESSION_MAX: "+this.SESSION_MAX),this.session_count>this.SESSION_MAX&&this.stopGame()):(statusView.updateHitDisplay(!1),statusModel.decLives(),lives=statusModel.getLives(),console.log("lives: "+
lives),statusView.updateLivesDisplay(),0>=lives&&(console.log("call stopGame()"),this.stopGame()));c&&a&&(this.interval_mode%=2,this.baseNoteProps=statusModel.getBaseNoteProperties(statusModel.getLevel()),this.baseNoteSpec=this.baseNoteProps.key+"/"+this.baseNoteProps.octave,this.intervalProps=statusModel.getRandomIntervalProperties(statusModel.getLevel()),a=this.intervalProps.size,e=this.intervalProps.quality,"B"===this.baseNoteSpec[1]&&"E"!==this.baseNoteSpec[0]&&4!==a&&5!==a&&"d"===e&&(this.intervalProps=
statusModel.getAltIntervalProperties()),"B"===this.baseNoteSpec[1]&&"F"===this.baseNoteSpec[0]&&4===a&&"d"===e&&(this.intervalProps=statusModel.getAltIntervalProperties()),"C"!==this.baseNoteSpec[0]&&"F"!==this.baseNoteSpec[0]&&"#"===this.baseNoteSpec[1]&&4!==a&&5!==a&&"A"===e&&(this.intervalProps=statusModel.getAltIntervalProperties()),"B"===this.baseNoteSpec[0]&&"#"===this.baseNoteSpec[1]&&5===a&&"A"===e&&(this.intervalProps=statusModel.getAltIntervalProperties()),this.intervalNoteSpec=statusModel.getIntervalNoteSpec(this.baseNoteSpec,
this.intervalProps.size,this.intervalProps.quality,this.clef_type),this.intervalNoteProps=Vex.Flow.keyProperties(this.intervalNoteSpec),0===this.interval_mode?(this.startx=105,note_specs={0:{note_names:[this.baseNoteSpec,this.intervalNoteSpec],accidentals:[this.baseNoteProps.accidental,this.intervalNoteProps.accidental],note_dur:"w"},length:1}):1===this.interval_mode&&(this.startx=85,a=Math.round(1E3*Math.random())%2,d>=statusModel.SWITCH_LEVEL&&1===a?(a=this.intervalNoteSpec,e=this.baseNoteSpec,
f=this.intervalNoteProps.accidental,g=this.baseNoteProps.accidental):(a=this.baseNoteSpec,e=this.intervalNoteSpec,f=this.baseNoteProps.accidental,g=this.intervalNoteProps.accidental),note_specs={0:{note_names:[a],accidentals:[f],note_dur:"h"},1:{note_names:[e],accidentals:[g],note_dur:"h"},length:2}),this.displayButtonLabels(),notationController.drawClef("staff_paper",this.stave,this.clef_type),notationController.hideNote("staff_paper",this.stave),2!==this.interval_mode?notationController.drawNotes("staff_paper",
this.stave,note_specs,this.timeSig,this.startx):($(".listen_box").show(),g=this.baseNoteProps.key,f=this.intervalNoteProps.key,e=Flash.Interval.intervalSoundNameProperties(g),a=Flash.Interval.intervalSoundNameProperties(f),g="CB"===g||"CBB"===g?parseInt(this.baseNoteProps.octave)-1:"B#"===g||"B##"===g?parseInt(this.baseNoteProps.octave)+1:parseInt(this.baseNoteProps.octave),f="CB"===f||"CBB"===f?parseInt(this.intervalNoteProps.octave)-1:"B#"===f||"B#"===f?parseInt(this.intervalNoteProps.octave)+1:
parseInt(this.intervalNoteProps.octave),e=g+e.offset,f+=a.offset,a=Math.round(1E3*Math.random())%2,d>=statusModel.SWITCH_LEVEL&&1===a?(this.snd1=Flash.Interval.intervalSounds.table.sounds[f].sound,this.snd2=Flash.Interval.intervalSounds.table.sounds[e].sound):(this.snd1=Flash.Interval.intervalSounds.table.sounds[e].sound,this.snd2=Flash.Interval.intervalSounds.table.sounds[f].sound),soundManager.play(this.snd1.id,{onfinish:function(){soundManager.play(b.snd2.id)}})),statusModel.addPoint(),statusModel.calculateScore(),
this.interval_mode+=1);c&&(statusModel.addAttempt(),Games.Common.displayScore())};Flash.Interval.GameController.prototype.stopGame=function(){var a,b;a=statusModel.isLevelAdvance();b=0<statusModel.getLives()?!1:!0;a&&(statusModel.advanceLevel(),statusModel.addBonus(),statusModel.setStart(!1));(this.session_count>=this.SESSION_MAX||b)&&Games.Common.displaySessionAlert(!1,b,a);return this};
Flash.Interval.GameController.prototype.resetGame=function(){statusModel.setIsTimeout(!1);statusModel.setTimeInterval(this.timeOut);statusModel.setPoints(0);statusModel.setAttempts(0);this.clef_type="treble";Games.Common.displayScore()};Flash.Interval.GameController.prototype.getStart=function(){return statusModel.getStart()};
Flash.Interval.GameController.prototype.updateLevel=function(){this.clef_type=1===statusModel.getLevel()%2?"treble":"bass";statusModel.setClef(this.clef_type);Games.Common.displayScore();statusModel.setStart(!1);Games.Common.displaySessionAlert(!0,!1,!1)};Flash.Interval.StatusModel=function(){this.MAX_LEVEL=30;this.MIN_ATTEMPTS=12;this.MIN_PERCENT=80;this.BONUS_INC=this.BONUS=5;this.BONUS_LEVEL=0;this.MAX_LIVES=5;this.SWITCH_LEVEL=8;this.score=this.attempts=this.points=0;this.level=1;this.bonus=0;this.lives=5;this.start=!1;this.timeInterval=this.TIMEOUT;this.isTimeOut=!1;this.value_code=this.input_code=0;this.clef="treble";this.base_notes="C F G D E A B BB EB DB GB F# AB C# CB FB G# D# E# A# B#".split(" ");this.base_note_bounds=[3,4,5,6,7,8,9,10,11,
12,13,14,15,16,17,18,19,20,21,21,21,21,21,21,21,21,21,21,21,21];this.interval_bounds=[4,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,23,23,23,23,23,23,23,23,23];this.interval_index=[2,12,6,9,5,22,16,20,15,19,1,0,3,4,7,8,10,11,13,14,17,18,21];this.temp_interval_props=[];this.top_scores=[];this.top_times=[];this.top_date_strings=[];this.top_time_strings=[];this.hi_score=Modernizr.localstorage?(this.old_score=parseInt(localStorage.getItem("hiscore_interval")))?this.old_score:0:0};
Flash.Interval.StatusModel.prototype.getTime=function(){return this.time};Flash.Interval.StatusModel.prototype.setTime=function(a){this.time=a};Flash.Interval.StatusModel.prototype.setDate=function(){this.date=new Date;this.date_time=this.date.getTime()};Flash.Interval.StatusModel.prototype.getDateTime=function(){return this.date_time};
Flash.Interval.StatusModel.prototype.getDateString=function(){var a=""+(this.date.getMonth()+1),b=10>this.date.getDate()?"0"+this.date.getDate():this.date.getDate();return a+"-"+b+"-"+this.date.getFullYear()};Flash.Interval.StatusModel.prototype.getTimeString=function(){var a=""+this.date.getHours(),b=10>this.date.getMinutes()?"0"+this.date.getMinutes():this.date.getMinutes(),c=10>this.date.getSeconds()?"0"+this.date.getSeconds():this.date.getSeconds();return a+":"+b+":"+c};
Flash.Interval.StatusModel.prototype.addPoint=function(){this.points+=1};Flash.Interval.StatusModel.prototype.setPoints=function(a){this.points=a};Flash.Interval.StatusModel.prototype.getPoints=function(){return this.points};Flash.Interval.StatusModel.prototype.addAttempt=function(){this.attempts+=1};Flash.Interval.StatusModel.prototype.setAttempts=function(a){this.attempts=a};Flash.Interval.StatusModel.prototype.getAttempts=function(){return this.attempts};
Flash.Interval.StatusModel.prototype.getPercent=function(){return Math.floor(this.points/this.attempts*100)};Flash.Interval.StatusModel.prototype.calculateScore=function(){this.score+=this.points*this.level};Flash.Interval.StatusModel.prototype.addBonus=function(){this.bonus=this.BONUS*this.level;this.score+=this.bonus};Flash.Interval.StatusModel.prototype.getBonus=function(){return this.bonus};Flash.Interval.StatusModel.prototype.setScore=function(a){this.score=a};
Flash.Interval.StatusModel.prototype.getScore=function(){return this.score};Flash.Interval.StatusModel.prototype.getHiScore=function(){return this.hi_score};Flash.Interval.StatusModel.prototype.setHiScore=function(a){this.hi_score=a;Modernizr.localstorage&&localStorage.setItem("hiscore_interval",this.hi_score)};Flash.Interval.StatusModel.prototype.setLevel=function(a){this.level=a;this.level>this.BONUS_LEVEL&&(this.BONUS+=this.BONUS_INC)};Flash.Interval.StatusModel.prototype.getLevel=function(){return this.level};
Flash.Interval.StatusModel.prototype.advanceLevel=function(){this.setLevel(this.level<this.MAX_LEVEL?this.level+=1:this.MAX_LEVEL);return this};Flash.Interval.StatusModel.prototype.decLives=function(){--this.lives;0>this.lives&&(this.lives=0)};Flash.Interval.StatusModel.prototype.setLives=function(a){this.lives=a};Flash.Interval.StatusModel.prototype.getLives=function(){return this.lives};Flash.Interval.StatusModel.prototype.setStart=function(a){this.start=a};
Flash.Interval.StatusModel.prototype.getStart=function(){return this.start};Flash.Interval.StatusModel.prototype.setTimeInterval=function(a){this.timeInterval=a};Flash.Interval.StatusModel.prototype.getTimeInterval=function(){return this.timeInterval};Flash.Interval.StatusModel.prototype.setIsTimeout=function(a){this.isTimeOut=a};Flash.Interval.StatusModel.prototype.getIsTimeout=function(){return this.isTimeOut};
Flash.Interval.StatusModel.prototype.getBaseNoteProperties=function(a){var b=[],c,d,e=this.base_note_bounds[a-1],f=Math.round(1E3*Math.random()%4)+2;b[0]=this.base_notes[0];for(c=1;c<e;c++)d=Math.round(1E3*Math.random())%(c+1),b[c]=b[d],b[d]=this.base_notes[c];this.base_note=b[0];b=Vex.Flow.keyProperties.note_values[this.base_note].index;switch(this.clef){case "treble":4>f&&(f=6>b?4:3);4>a?4<f&&(f=2<b?4:5):4<f&&(f=4);break;case "bass":3>f&&1>b&&(f=3),4>a?2<f&&(f=4<b?2:3):2<f&&(f=1<b?2:3)}return Vex.Flow.keyProperties(this.base_note+
"/"+f,this.clef)};
Flash.Interval.StatusModel.prototype.getRandomIntervalProperties=function(a){var b=this.interval_bounds[a-1],c,d=[];a=[];var e;for(e=0;e<b;e++)c=this.interval_index[e],d[e]=Flash.Interval.intervalProperties(c),d[e].target=!1;a[0]=d[0];for(e=1;e<b;e++)c=Math.round(1E3*Math.random())%(e+1),a[e]=a[c],a[c]=d[e];b=3>a.length?a.length:3;for(e=0;e<b;e++)this.temp_interval_props[e]=a[e];this.alt_props=a[3];this.alt_sound_props=3<=this.level?a[4]:null;this.reserve_props=4<=this.level?a[5]:null;c=Math.round(100*
Math.random())%b;a=a[c];this.value_code=c;a.target=!0;return a};Flash.Interval.StatusModel.prototype.getTempIntervalProperties=function(){return this.temp_interval_props};Flash.Interval.StatusModel.prototype.getAltIntervalProperties=function(){var a=this.alt_props;a.target=!0;this.temp_interval_props[this.value_code]=a;this.alt_props=this.reserve_props;return a};Flash.Interval.StatusModel.prototype.getAltSoundProperties=function(){return this.alt_sound_props};
Flash.Interval.StatusModel.prototype.getIntervalNoteSpec=function(a,b,c,d){d=Vex.Flow.keyProperties(a).key;var e=parseInt(Vex.Flow.keyProperties(a).octave),f=Vex.Flow.keyProperties.note_values[d].index;a=Vex.Flow.keyProperties.note_values[d].accidental;var g="",e=7>f+b-1?e:e+1,f=(f+b-1)%7,g="",g=(g=8===b?a:Flash.Interval.accidental(d,b,c))?g:"";return g=Vex.Flow.integerToNoteLetter(f)+g.toUpperCase()+"/"+e};Flash.Interval.StatusModel.prototype.setInputCode=function(a){this.input_code=a};
Flash.Interval.StatusModel.prototype.getMatch=function(){return this.input_code===this.value_code};Flash.Interval.StatusModel.prototype.isLevelAdvance=function(){return this.getPercent()>=this.MIN_PERCENT&&this.getAttempts()>=this.MIN_ATTEMPTS-1?!0:!1};Flash.Interval.StatusModel.prototype.setClef=function(a){this.clef=a;return this};Flash.Interval.StatusModel.prototype.getClef=function(a){return this.clef=a};Flash.Interval.StatusView=function(){var a,b,c,d,e,f,g,h=[],k,l;this.initLivesDisplay=function(c,d){b=Raphael(c,60,20);for(a=0;a<d;a++)h[a]=b.circle(10*(a+1),5,4.5).attr({fill:"green",stroke:"#000"})};this.updateLivesDisplay=function(){k=h.length;0<k&&(h[k-1].remove(),h.pop())};this.removeLivesDisplay=function(){b.remove()};this.drawStatusBar=function(a,b,e,f){c=Raphael(a,b,e,f);d=c.rect(0,0,e,f);d.attr({stroke:"red",fill:"#202000"})};this.initHitDisplay=function(a){e=Raphael(a,0,0);f=e.path("M 5 18 L 17 30 L 33 2 L 17 23 Z").attr({stroke:"#447",
"stroke-width":1});g=e.path("M 5 5 L 35 35 M 35 5 L 5 35").attr({stroke:"#447","stroke-width":5});f.hide();g.hide()};this.removeHitDisplay=function(){e.remove();$(".hit_box").hide()};this.updateHitDisplay=function(a){a?(f.attr({stroke:"#0c2",fill:"#0c2"}),g.hide(),f.show()):(g.attr({stroke:"#f00"}),f.hide(),g.show());this.startHitTimer();$(".hit_box").show()};this.startHitTimer=function(){var a=this;l=setTimeout(function(){a.stopHitTimer()},600)};this.stopHitTimer=function(){f.hide();g.hide();$(".hit_box").hide();
clearTimeout(l)}};Flash.Interval.StatusView.prototype.displayInputLabels=function(a,b){var c,d,e,f=btn_array.length;for(c=0;c<f;c++)d=a[c],e=b[c],$(d).html(e)};Flash.Interval.StatusView.prototype.displayTime=function(a,b){var c="00:",d=0<=b?""+b:""+(b+1);10>b&&(c="00:0");$(a).html(c+d)};Flash.Interval.StatusView.prototype.displayLevel=function(a,b){var c=""+b;$(a).html(c)};Flash.Interval.StatusView.prototype.displayPoints=function(a,b,c){b=""+b+"/"+c;$(a).html(b)};
Flash.Interval.StatusView.prototype.displayPercent=function(a,b,c){b=""+(0<c?Math.round(b/c*100):0)+"%";$(a).html(b)};Flash.Interval.StatusView.prototype.displayScore=function(a,b){var c=""+b;$(a).html(c)};Flash.Interval.StatusView.prototype.displayHiScore=function(a,b){var c=""+b;$(a).html(c)};
